# Generated by Django 2.2.10 on 2020-08-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_note_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('U', 'Uncategorized'), ('W', 'Work'), ('F', 'Family Affair'), ('S', 'Study'), ('P', 'Personal')], default='U', max_length=200),
        ),
    ]
