# Generated by Django 2.2.10 on 2020-08-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_auto_20200830_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='note_category',
            field=models.CharField(default='U', max_length=200),
        ),
    ]
