# Generated by Django 2.2.10 on 2020-08-31 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_auto_20200830_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='note_category',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='note.Category'),
        ),
    ]
