# Generated by Django 2.2.10 on 2020-09-01 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_auto_20200831_0626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
